pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = ''
        AWS_REGION = 'us-east-1'
        ECR_REPOSITORY = 'an-example-repository-for-testing'
        IMAGE_TAG = "latest"
        DOCKER_IMAGE_NAME = 'testing-application'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'ls'
                    sh 'echo "admin" | docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG -f AWSLambdaForTestingProject/Dockerfile .'
                }
            }
        }

stage('Login To ECR') {
    steps {
        script {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'prm013']]) {
                sh '''
                    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050152649.dkr.ecr.us-east-1.amazonaws.com
                '''
            }
        }
    }
}

        stage('Tag Docker Image') {
            steps {
                script {
                    sh "echo "admin" | docker tag $DOCKER_IMAGE_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
                }
            }
        }

        stage('Push to ECR') {
            steps {
                script {
                    sh "echo "admin" | docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
                }
            }
        }
    }

    post {
        success {
            echo 'Image pushed to ECR successfully'
        }
        failure {
            echo 'There was an error during the pipeline execution.'
        }
    }
}